# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Poetry
      run: | 
        pipx install poetry

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.2"
        cache: "poetry"

    - name: Set Poetry environment
      run: |
        poetry env use 3.12.2

    - name: Install dependencies
      run: |
        poetry install --no-root
        poetry run pip install mlx

    - name: Test with pytest
      run: |
        poetry run pytest